MAX_RESULT_HISTORY = 100_000

DEFAULT_BATCH_SIZE = 1024 * 1024 * 1024
DEFAULT_BATCH_NUM_FILES = 10_000
DEFAULT_NUM_MASTER_PROCESSES = 5
DEFAULT_MASTER_SCAN_DEPTH = 3
DEFAULT_QUEUE_THRESHOLD = 1000
DEFAULT_MASTER_BIND_HOST = "0.0.0.0"
DEFAULT_MASTER_CLAIM_PORT = 5555
DEFAULT_MASTER_BATCH_PORT = 5556
DEFAULT_MASTER_RESULT_PORT = 5557
DEFAULT_MASTER_HEARTBEAT_PORT = 5558
DEFAULT_MASTER_API_PORT = 8000
DEFAULT_COMPRESS_PATHS = False
DEFAULT_COMPRESS_MAX_DEPTH = 2
DEFAULT_HEARTBEAT_TIMEOUT = 15.0

DEFAULT_NUM_WORKER_PROCESSES = 5
DEFAULT_DST_HOST = "localhost"
DEFAULT_MASTER_HOST = "127.0.0.1"
DEFAULT_WORKER_CLAIM_PORT = 5555
DEFAULT_WORKER_RESULT_PORT = 5557
DEFAULT_WORKER_HEARTBEAT_PORT = 5558
DEFAULT_RSYNC_BIN = "rsync"
DEFAULT_RSYNC_ARGS = ""
DEFAULT_RETRY_LIMIT = 3
DEFAULT_HEARTBEAT_INTERVAL = 5.0

DEFAULT_TIMEZONE = "Asia/Seoul"
